### ISSUE TITLE
Bundling this as a Win Mac Linux application

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/local-backup-server#1]
https://www.npmjs.com/package/nexe
https://dev.to/jochemstoel/bundle-your-node-app-to-a-single-executable-for-windows-linux-and-osx-2c89
https://github.com/zeit/pkg

**Comment by Eik-S** [comment]
The binaries can now be build using pkg as explained in the __README__.
I would suggest adding them with a release of this repo to keep the repository size small.

**Comment by oliversauter** [comment]
WHAAT? This is already working? how nice is that! This makes me really excited. I will try this out asap :)

**Comment by Eik-S** [comment]
### TODOS for finishing local server applications:
- [ ] add interface for backup folder selection
- [ ] add task bar icon and context menu for changing the folder or shutting down the server
- [ ] run the server as a background process

For adding these functionalities to the executables, we should use a framework capable of exporting applications for win, osx, linux supporting context menus, tray icons...
I found https://www.sitepoint.com/cross-platform-desktop-app-nw-js/ and think nwjs is a nice framework for this purpose.
